<a href="https://colab.research.google.com/github/jiobu1/DS-Unit-1-Sprint-2-Statistics/blob/master/module3/DSPT5_123a_bayes2_starter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Example of a classifier

In [0]:
# EDA and data handling
import numpy as np
import pandas as pd

# Modeling
from sklearn.model_selection import train_test_split 
# training is to train model and work out alogorithms/ 
#testing try algorithms on unseen data and see if it works and has not been overfitted to training data
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [41]:
# read in the data
housing = pd.read_csv('/content/sample_data/california_housing_train.csv')
housing.shape

(17000, 9)

In [0]:
# reduce the size of the dataset
housing = housing.sample(500, random_state=42)

In [43]:
# show the data 
housing.head()

longitude  latitude  ...  median_income  median_house_value
10941    -120.87     37.77  ...         3.5959            142700.0
5250     -118.14     34.11  ...         8.1124            500001.0
10292    -120.05     36.98  ...         2.5288             61800.0
2266     -117.42     34.02  ...         4.2321            162800.0
6398     -118.26     33.97  ...         1.5326             90600.0

[5 rows x 9 columns]

In [44]:
# Describe the target 
housing['median_house_value'].describe()

count       500.000000
mean     217606.070000
std      126374.865826
min       27500.000000
25%      116750.000000
50%      185900.000000
75%      284175.000000
max      500001.000000
Name: median_house_value, dtype: float64

In [45]:
# create the target 
housing['high_price'] =np.where(housing['median_house_value']>=185900, 1, 0)
housing['high_price'].value_counts()

1    250
0    250
Name: high_price, dtype: int64

In [46]:
# establish the predictors and the target
X = housing.drop(['high_price', 'median_house_value'], axis=1)
X

longitude  latitude  ...  households  median_income
10941    -120.87     37.77  ...       923.0         3.5959
5250     -118.14     34.11  ...       414.0         8.1124
10292    -120.05     36.98  ...       697.0         2.5288
2266     -117.42     34.02  ...       858.0         4.2321
6398     -118.26     33.97  ...       362.0         1.5326
...          ...       ...  ...         ...            ...
10109    -119.81     34.45  ...       570.0         6.5173
12121    -121.44     38.62  ...       354.0         1.9107
15188    -122.27     37.90  ...       275.0         7.9556
16797    -123.15     39.74  ...       108.0         2.9306
10903    -120.84     35.32  ...       522.0         3.4762

[500 rows x 8 columns]

In [0]:
# establish the target
y = housing['high_price']

In [48]:
# train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
len(y_test)

150

In [0]:
# instantiate the classifier
mymodel = RandomForestClassifier()

In [50]:
# fit on the training data
mymodel.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
# predict on the testing data
y_pred = mymodel.predict(X_test)

In [52]:
# check out the first few neighborhoods
print(y_test.values[10:20], 'true values')
print(y_pred[10:20], 'predicted values')

[1 1 1 1 0 1 1 0 1 0] true values
[1 1 1 1 0 0 1 0 0 0] predicted values


In [53]:
# evaluate the model performance
metrics.accuracy_score(y_test, y_pred)

0.8333333333333334

## Confusion Matrix

In [54]:
# examine the confusion matrix
cm1 = metrics.confusion_matrix(y_test, y_pred)
cm1

array([[66, 11],
       [14, 59]])

In [55]:
#convert to dataframe
cm = pd.DataFrame(cm1, columns=['pred_0', 'pred_1'])
cm

pred_0  pred_1
0      66      11
1      14      59

* 59 true positives (TP): These are cases in which we predicted yes (pricey house), and it is indeed a pricey house.
* 66 true negatives (TN): We predicted no (cheap house), and the house is indeed cheap.
* 11 false positives (FP): We predicted yes (pricey house), but the house isn't pricey. (Also known as a "Type I error.")
* 14 false negatives (FN): We predicted no (cheap house), but the house is actually pricey. (Also known as a "Type II error.")

<div>
<img src="https://www.dataschool.io/content/images/2015/01/confusion_matrix2.png" width="500"/>

SOURCE: https://www.dataschool.io/simple-guide-to-confusion-matrix-terminology

In [65]:
# get the numbers
TN = cm['pred_0'].values[0]
FN = cm['pred_0'].values[1]
FP = cm['pred_1'].values[0]
TP = cm['pred_1'].values[1]
ALL = cm.values.sum()

print(TN, FN, FP, TP)

66 14 11 59


In [66]:
print('True Negatives:', TN)
print('False Negatives:', FN)
print('False Positives:', FP)
print('True Positives:', TP)
print('All:', ALL)

True Negatives: 66
False Negatives: 14
False Positives: 11
True Positives: 59
All: 150


**Accuracy:**  
Overall, how often is it correct?

In [68]:
print(f'Accuracy:{round((TP+TN)/ALL, 2)}')

Accuracy:0.83


**True Positive Rate:**   
When it's actually yes, how often does it predict yes?        
“Sensitivity” or “Recall”

In [71]:
print('True Positive Rate:{:.4f}'.format(TP/(TP + FN)))

True Positive Rate:0.8082


**False Positive Rate:**    
When it's actually no, how often does it predict yes?   
Also known as "Fall-out Rate"

In [76]:
print(f'False Positive Rate:{FP/(TN+FP):.4f}')

False Positive Rate:0.1429


**Precision:**     
When it predicts yes, how often is it correct?  
Also known as "Positive Predictive Value (PPV)"

In [77]:
print('Precision:{:.4f}'.format(TP/(TP + FP)))

Precision:0.8429


**Specificity:**  
When it's actually no, how often does it predict no?    
also known as "True Negative Rate"

In [79]:
print('Specificity: {:.4f}'.format(TN/(TN+FP)))

Specificity: 0.8571


**Prevalence:**    
How often does the yes condition actually occur in our sample?  
actual yes/total

In [81]:
P = TP + FN
print('Prevalence:{:.4f}'.format(P/ALL))
#All pos = TP + FN (FN-positive)

Prevalence:0.4867


## Again

In [91]:
# House age
housing['housing_median_age'].describe()

count    500.000000
mean      29.872000
std       12.483561
min        4.000000
25%       19.000000
50%       30.000000
75%       38.250000
max       52.000000
Name: housing_median_age, dtype: float64

In [0]:
# Create a target
housing['old'] = np.where(housing['housing_median_age']>= 38, 1, 0)

In [0]:
# establish the predictors and the target
X = housing.drop(['old', 'housing_median_age', 'high_price'], axis=1)
y = housing['old']

In [94]:
# train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
len(y_test)

150

In [0]:
# instantiate the classifier
mymodel = RandomForestClassifier()

In [96]:
# fit on the training data
mymodel.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
# predict on the testing data
y_pred = mymodel.predict(X_test)

In [98]:
# check out the first few houses
print(y_test.values[:10], 'ground truth')
print(y_pred[:10], 'predictions')

[0 0 0 0 0 0 0 0 1 0] ground truth
[0 0 0 0 0 0 0 0 1 0] predictions


In [99]:
# evaluate the model performance
metrics.accuracy_score(y_test, y_pred)

0.8133333333333334

In [101]:
# examine the confusion matrix
cm = pd.DataFrame(metrics.confusion_matrix(y_test, y_pred), columns = ['pred_0', 'pred_1'])
cm

pred_0  pred_1
0     107       8
1      20      15

In [104]:
# get the numbers
TN = cm['pred_0'].values[0]
FN = cm['pred_0'].values[1]
FP = cm['pred_1'].values[0]
TP = cm['pred_1'].values[1]
ALL=cm.values.sum()

print(TN, FN, FP, TP)

107 20 8 15


In [105]:
print('Accuracy: {:.4f}'.format((TP + TN)/ ALL))
print('True Positive Rate: {:.4f}'.format(TP/ ( TP + FN)))
print('False Positive Rate: {:.4f}'.format( FP / (TN + FP)))
print('Precision: {:.4f}'.format( TP / (TP + FP)))
print('Specificity: {:.4f}'.format( TN / (TN + FP)))
print('Prevalence: {:.4f}'.format( ((TP + FN)/ALL)))

Accuracy: 0.8133
True Positive Rate: 0.4286
False Positive Rate: 0.0696
Precision: 0.6522
Specificity: 0.9304
Prevalence: 0.2333


## Terminology

| Bayes term | Bayes formula | Confusion Matrix term | Confusion Matrix formula| Alternative CM term | 
|:-|:-|:-|:-|:-|
| prior | P(A) | prevalence | (TP + FN) / (TP+TN+FP+FN) | ? |
| posterior | P(A given B) | Positive Predictive Value (PPV) | TP / (TP + FP) | precision |
| conditional | P(B given A) | True Positive Rate (TPR)  |TP / (TP + FN) | sensitivity, recall |
| marginal | P(B) | queue rate | TP + FP | ? |  
| prior complement | P(not A) or 100-P(A) | prevalence complement | 1-prevalence | ? |
| ? | P(not B given not A) | True Negative Rate (TNR) | TN / (FP + TN) | specificity |
| ? | P(B given not A) | False Positive Rate (FPR) | FP / (FP+TN) | fall-out rate, false alarm rate |
| ? | P(not B given A) | False Negative Rate (FNR) | FN / (TP + FN) | miss rate |
|?|?|accuracy|(TP + TN) / (TP+TN+FP+FN)|?|
|?|?|error rate|(FP + FN) / (TP+TN+FP+FN)|misclassification rate|


**Abbreviations**  
A: Hypothesized Data       
B: Observed Data         
TP: True Positive  
TN: True Negative  
FP: False Positive  
FN: False Negative  
 
^ Note: Sometimes in Bayesian statistics the following terms are used instead:
 
* prior = hypothesis
* posterior = updated hypothesis
* conditional = likelihood
* marginal = model evidence

## Problem 1. Drunk Drivers

imagine that individuals are taking a breathalyzer test with 
* an 8% false positive rate, 
* a 100% true positive rate, 
* our prior belief about drunk driving in the population is 1/1000. 
* What is the probability that a person is drunk after one positive breathalyzer test?

In [0]:
# write a function
def prob_drunk_given_positive(prob_drunk_prior, false_positive_rate, true_positive_rate):
  prob_non_drunk = 1-prob_drunk_prior
  numerator = true_positive_rate * prob_drunk_prior
  demoninator = ((true_positive_rate * prob_drunk_prior) + (false_positive_rate * prob_non_drunk))
  posterior = numerator/ demoninator
  return posterior

In [108]:
# Probability that a person is drunk after one breathalyzer test:
prob_drunk_given_positive(1/1000, .08, 1)

0.012357884330202669

In [0]:
def bayes_theorem(p_a, p_b_given_a, p_b_given_not_a, confidence):
    """
    Calculates the probability of A given B, P(A|B)
    Also calculates the number of tests that need to be run
    to get to the desired confidence. Maximum number of tests: 100

    @param p_a: Float, P(A), prior belief
    @param p_b_given_a: Float, P(B|A), true positive
    @param p_b_given_not_a: Float, P(B|!A), false positive
    @param confidence: Float, target rating
    @return: String, P(A|B) and the number of tests needed
    """
    p_a_given_b = 0
    exp = 0
    while p_a_given_b <= confidence:
        exp += 1
        assert exp < 100, "Test Failed, confidence level untenable."
        not_a = 1.0 - p_a
        p_b = p_b_given_a * p_a + p_b_given_not_a**exp * not_a
        p_a_given_b = (p_b_given_a * p_a) / p_b
    return f"P(A|B) is {p_a_given_b * 100:.3f}% after {exp} tests"

In [112]:
bayes_theorem(1/1000, 1, .08, .95)

'P(A|B) is 96.069% after 4 tests'

## Problem 2: Marginal is provided
Solving for the posterior is not too complicated when the marginal probability is provided for you. 

Suppose we have an online website where we sell a gizmo. Consider the case where a website-visitor clicks to expand the gizmo's product description. What is the probability that they will then purchase the gizmo?

Let’s assume some details:  
* 10 percent of site visitors buy the gizmo.  That's the prior: P(buy).
* 7 percent of site visitors that purchased the gizmo also clicked on the description. That's the conditional: P(click|buy).
* 5 percent of site visitors click on the product description. That's the marginal: P(click).
* What percent of site visitors will purchase the gizmo after clicking on the description? That's the posterior: P(buy|click).

Let’s plug what we know into the theorem:
* P(A|B) = P(B|A) * P(A) / P(B)   
* P(buy|click) = P(click|buy) * P(buy) / P(click)

In [0]:
# input the prior, marginal, and conditional.
p_a = .1
p_b = .05
p_b_given_a = .07

In [0]:
# write the formula
def bayes_w_marginal(prior, marginal, conditional):
  posterior = (conditional*prior)/marginal
  return posterior

In [122]:
# plug it in
result = bayes_w_marginal(p_a, p_b, p_b_given_a)
result

0.14

## Problem 3: No marginal provided!
Solving for the posterior is a little harder when the marginal is not provided; most real-world problems fall into this pattern.

Consider the case where we receive an email and the spam detector flags it (i.e., puts it in the spam folder). What is the probability it was actally spam?

Let’s assume some details:  
* 2 percent of the email we receive is spam -- that's the prior: P(Spam). 
* the spam detector is really good and when an email is spam, it flags it 99 percent of the time -- that's the conditional: P(Flagged|Spam).   
* When an email is not spam, it will flag it with a very low rate of 0.1 percent -- that's the fall-out rate: P(Flagged|not Spam).  
* What is the probability that a flagged email is actually spam? -- that's the posterior: P(Spam|Flagged) 

Let’s plug what we know into the theorem:
* P(A|B) = P(B|A) * P(A) / P(B)   
* P(Spam|Flagged) = P(Flagged|Spam) * P(Spam) / P(Flagged)

We don’t know P(B), that is P(Flagged), but we can calculate it as follows:
* P(B) = P(B|A) * P(A) + P(B|not A) * P(not A) 
* P(Flagged) = P(Flagged|Spam) * P(Spam) + P(Flagged|not Spam) * P(not Spam)

In [0]:
# input the prior, conditional, and fall-out rate.
p_a = .02
p_b_given_a=.99
p_b_given_not_a = .001

In [0]:
# write the formula
def bayes_no_marginal(prior, conditional, cond_complement):
  not_a = 1 - prior
  marginal = conditional*prior+cond_complement*not_a
  posterior = (conditional*prior)/marginal
  return posterior

In [136]:
# plug it in
bayes_no_marginal(p_a, p_b_given_a, p_b_given_not_a)

0.9528392685274303

## Problem 4. No marginal (again)


Let’s assume some details:  
* the condition occurs in 2% of the population -- that's the prior: P(sick). 
* when a patient is actually sick, the classifier flags them as sick 72 percent of the time -- that's the conditional: P(Flagged|Sick).   
* when the classifier says they are not sick, this is true 97 percent of the time. That's P(not Flagged | not Sick)
* What is the probability that a flagged patient is actually sick? -- that's the posterior: P(Sick|Flagged).

We don't know the marginal P(B), and we don't know the fall-out rate -- P(Flagged|not Sick) -- but we can calculate them using the formulas:

* P(B) = P(B|A) * P(A) + P(B|not A) * P(not A)
* P(B|not A) = 1 – P(not B|not A)

Which translates to: 
* P(Flagged) = P(Flagged|Sick) * P(Sick) + P(Flagged|not Sick) * P(not Sick)
* P(Flagged|not Sick) = 1 - P(not Flagged|not Sick)

In [0]:
# input the prior, conditional, and P(not B|not A).
p_a = .02
p_b_given_a =.72
p_not_b_given_not_a=.97

In [0]:
# write the formula:
def bayes_no_marginal_no_fallout(prior, conditional, p_not_b_given_not_a):
  not_a = 1-prior
  p_b_given_not_a  = 1 - p_not_b_given_not_a
  marginal = conditional * prior + p_b_given_not_a * not_a
  posterior = (conditional*prior)/marginal
  return posterior

In [139]:
# plug it in:
bayes_no_marginal_no_fallout(p_a, p_b_given_a, p_not_b_given_not_a)

0.32876712328767105

Sources:  
* http://learningwithdata.com/bayes-primer.html#bayes-primer  
* https://machinelearningmastery.com/intuition-for-bayes-theorem-with-worked-examples/  
* https://www.bayestheorem.net/  
* https://lucdemortier.github.io/articles/16/PerformanceMetrics
* https://towardsdatascience.com/machine-learning-an-error-by-any-other-name-a7760a702c4d
* https://ncss-wpengine.netdna-ssl.com/wp-content/themes/ncss/pdf/Procedures/NCSS/Binary_Diagnostic_Tests-Single_Sample.pdf
* https://www.dataschool.io/simple-guide-to-confusion-matrix-terminology/
* https://online.stat.psu.edu/stat507/node/71/